eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
  instance:
    instance-id: ${spring.cloud.client.ip-address}:${server.port}
    prefer-ip-address: true
spring:
  application:
    name: api-gateway
  redis:
    host: 116.62.243.88
    port: 6379
zuul:
  routes:
#       /myProduct/product/list -> /product/product/list
    aaaaa:
      path: /myProduct/**
      serviceId: product

#    简介写法
#    product: /myProduct/**
#    排除某些路由
  ignored-patterns:
      -  /**/product/listForOrder

#      全部服务忽略敏感头，全部服务都可传递cookie
  sensitive-headers:
management:
  security:
    enabled: false

#设置zuul超时时间,默认一秒，在访问创建订单这个接口会报错
hystrix:
  command:
    default:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 5000





