eureka:
  client:
    service-url:
      defaultZone: http://localhost:8762/eureka/, http://localhost:8761/eureka/
    register-with-eureka: true
  server:
    enable-self-preservation: false
spring:
  application:
    name: server
#server:
#  port: 8761

