spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password: 123456
    url: jdbc:mysql://10.11.48.193:3306/sell?serverTimezone=Asia/Shanghai&characterEncoding=utf-8&useSSL=false
  application:
    name: product
  jpa:
    show-sql: true
  rabbitmq:
    host: 10.11.62.60
    port: 5672
    username: guest
    password: guest


eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
  instance:
    instance-id: ${spring.cloud.client.ip-address}:${server.port}
    prefer-ip-address: true





